var _createClass=function(){function b(a,b){for(var d=0;d<b.length;d++){var c=b[d];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}return function(a,e,d){e&&b(a.prototype,e);d&&b(a,d);return a}}();function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}
var Benefit=function(){function b(a,e,d,c){_classCallCheck(this,b);this.benefitName=a;this.benefitText=e;this.benefitNumber=d;this.benefitURL=c}_createClass(b,[{key:"showBenefit",value:function(){var a=this;bootbox.alert({size:"large",title:"<b>"+this.benefitNumber+"</b> appears to be your lucky number!",message:"<b>"+this.benefitNumber+"</b> means: "+this.benefitName+", which is "+this.benefitText,callback:function(){window.location=a.benefitURL}})}},{key:"benefitName",get:function(){return this._benefitName},
set:function(a){this._benefitName=a}},{key:"benefitNumber",get:function(){return this._benefitNumber},set:function(a){this._benefitNumber=a}},{key:"benefitText",get:function(){return this._benefitText},set:function(a){this._benefitText=a}},{key:"benefitURL",get:function(){return this._benefitURL},set:function(a){this._benefitURL=a}}]);return b}(),BenefitsArray=[];
BenefitsArray.push(new Benefit("ASME Access Engineering","an online tool powered by McGraw-Hill Education contains more than 600 categorized volumes and references, in addition to Curriculum Maps in thousands of engineering fields.",1,"https://m.facebook.com/ASME.Alexandria.University/?fref=hovercard"));
BenefitsArray.push(new Benefit("E-Mentoring Program","one-to-one advice that provide you with career-guiding insights, help you solve engineering problems or expand your networking opportunities with professionals.",2,"https://m.facebook.com/ASME.Alexandria.University/?fref=hovercard"));
BenefitsArray.push(new Benefit("ASME SmartBrief","a frequent e-newsletter especially for mechanical engineers that provide them with a quick digest of the latest engineering news and trends from around the world and across their profession.",3,"https://m.facebook.com/ASME.Alexandria.University/?fref=hovercard"));
BenefitsArray.push(new Benefit("Mechanical Engineering Magazine","a monthly publication that keeps you updated with the latest technology worldwide. It delivers an interdisciplinary view into engineering trends and breakthroughs.",4,"https://m.facebook.com/ASME.Alexandria.University/?fref=hovercard"));BenefitsArray.push(new Benefit("Internships and more!","attending regional and international conferences and getting internships and scholarships.",5,"https://m.facebook.com/ASME.Alexandria.University/?fref=hovercard"));
var canvas=document.querySelector("canvas"),height=canvas.height,width=canvas.width,rotationAngle=0,wheel=new Image,arrow=new Image;wheel.addEventListener("load",function(){arrow.addEventListener("load",function(){MainDrawFunction()},!1)},!1);wheel.src="img/wheel.png";arrow.src="img/arrow.png";var button=document.querySelector("button");
button.addEventListener("click",function(){switch(Math.round(180/Math.PI*Math.asin(Math.sin(rotationAngle)))){case 0:BenefitsArray[0].showBenefit();break;case 72:BenefitsArray[1].showBenefit();break;case 36:BenefitsArray[2].showBenefit();break;case -36:BenefitsArray[3].showBenefit();break;case -72:BenefitsArray[4].showBenefit()}},!1);
function MainDrawFunction(){if(canvas.getContext){var b=canvas.getContext("2d");b.setTransform(1,0,0,1,0,0);b.clearRect(0,0,width,height);b.drawImage(wheel,0,0);b.translate(width/2,height/2);b.rotate(rotationAngle);b.drawImage(arrow,-30,-20);rotationAngle+=Math.PI/180*72}else alert("Canvas isn't supported")}function displayTheBenefit(){}window.setInterval(MainDrawFunction,500);