#!/usr/bin/env sh
# 
# start: starts a jekyll server listening to port 4000 by default
#
# Author: Ahmed Khaled <ahmed.khaled1512@yahoo.com>
#
# License: ISC
#
# Usage: ./scripts/start
#
# You can set host port by setting the envrionment variable HOST
# for example PORT=5000 ./scripts/start
# and it can be accessible through https://localhost:5000
# 
# If you had a problem installing new gems run `chown -R jekyll:jekyll .`
# inside the container
#

JEKYLL_VERSION=4.2.0
PORT="${PORT:=4000}"
docker run -p $PORT:4000 \
           --rm \
           -v "$PWD:/srv/jekyll" \
           -e GEM_HOME="/srv/jekyll/gems" \
           -it "jekyll/jekyll:$JEKYLL_VERSION" \
           jekyll serve --drafts
